#Agency
exception.resources.agency.not_found=Agency with URN {0} not found

# Dataset
exception.resources.dataset.not_found=Dataset with URN {0} not found
exception.resources.dataset.version_not_found=Dataset version with URN {0} not found
exception.resources.dataset.last_version_not_found=Last version of dataset with urn {0} not found
exception.resources.dataset.max_reached_in_operation=The maximum sequence code for datasetVersion in operation {0} has been reached
exception.resources.dataset.empty_datasources=You need to provide at least one datasource for dataset {0}
exception.resources.dataset.empty_data=The dataset {0} has no data. 

# Datasource
exception.resources.datasource.not_found=Datasource with URN {0} not found

# Publication
exception.resources.publication.not_found=Publication with URN {0} not found
exception.resources.publication.version_not_found=Publication version with URN {0} not found
exception.resources.publication.last_version_not_found=Last version of publication with urn {0} not found
exception.resources.publication.max_reached_in_operation=The maximum sequence code for publicationVersion in operation {0} has been reached

# Chapters
exception.resources.chapter.not_found=Chapter with URN {0} not found
exception.resources.chapter.not_found_in_publication_version=Chapter with URN {0} not exists in publication version with URN {1}

# Cubes
exception.resources.cube.not_found=Cube with URN {0} not found

# Query
exception.resources.query.not_found = Query with URN {0} not found

# Identifiable Statistical Resource
exception.resources.identifiable_statistical_resource.not_found = Identifiable Statistical Resource with URN {0} not found
exception.resources.identifiable_statistical_resource.urn_duplicated=Identifiable statistical resource with URN {0} already exists

# Life cycle statistical resource
exception.resources.life_cycle.wrong_proc_status = Resource with URN {0} has an invalid procStatus for carry out this action. Allowed procStatus are\: {1} 

# External items
exception.resources.external_item.urn.not_published = Metadata {0} references a external resource with URN {1} that is not published
exception.resources.external_item.urn_internal.not_published = Metadata {0} references a external resource with URN INTERNAL {1} that is not published

# Tasks
exception.resources.task.error                                       = An error has occurred while preparing the task in background. Details: {0}
exception.resources.task.error.max_current_jobs                      = The maximum number of jobs in background is reached
exception.resources.task.error.not_found                             = Job with key {0} not found
exception.resources.task.error.server_down                           = The server was down while there was a job in background was running